title: SaiDz.My.ID
url: https://m.saidz.my.id
baseurl: "" # jika menggunakan custom domain kosongkan ini

# Atur permalink sesuai keinginan
permalink: /:categories/:title

# Plugins GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # tambahkan plugin lain yang kompatibel dengan GitHub Pages

# Exclude (jika ada file yang tidak ingin diproses oleh Jekyll)
exclude:
  - .github
  - README.md
theme: minima
